database:
  dsn: "postgres://demo:demo@localhost:5432/demo"
  max_conns: 20

table:
  name: "demo_table"

generator:
  count: 100000
  part_size: 500

default_cfg:
  varchar:
    length: 50
  timestamp:
    min: 1990-01-01 00:00:00
    max: 2025-01-01 00:00:00

fields.custom:
  f_id:
    skip: true
  f_varchar:
    in:
      - a
      - b